# Generated by Django 2.2.5 on 2020-06-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, null=True)),
                ('Email', models.EmailField(max_length=20, null=True)),
                ('Mobile', models.IntegerField(null=True)),
            ],
        ),
    ]
