# Generated by Django 2.2.5 on 2020-06-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_Register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_register',
            name='Mobile',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
