# Generated by Django 2.2.5 on 2020-06-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_Register', '0002_auto_20200610_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher_register',
            old_name='Name',
            new_name='Teacher_Name',
        ),
    ]
