# Generated by Django 2.2.5 on 2020-06-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_Register', '0003_auto_20200610_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_register',
            name='Email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_register',
            name='Teacher_Name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
