# Generated by Django 2.2.5 on 2020-06-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_Register', '0004_auto_20200612_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_register',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
