# Generated by Django 2.2.5 on 2020-07-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_Register', '0005_auto_20200612_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_signUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=40, null=True)),
                ('Password', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
