# Generated by Django 2.2.5 on 2020-07-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_Register', '0006_teacher_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_signup',
            name='Role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('user', 'Users')], max_length=20, null=True),
        ),
    ]
