# Generated by Django 2.2.5 on 2020-07-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_Register', '0007_teacher_signup_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_signup',
            name='Role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('user', 'user')], max_length=20, null=True),
        ),
    ]
