# Generated by Django 2.2.5 on 2020-07-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_Register', '0008_auto_20200719_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_register',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Submited', 'Submited')], max_length=12, null=True),
        ),
    ]
