# Generated by Django 2.2.5 on 2020-06-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.CharField(max_length=15)),
                ('Branch', models.CharField(max_length=15)),
                ('Teacher', models.CharField(max_length=15)),
                ('Regular_Punctual', models.CharField(max_length=15)),
                ('Knowledge', models.CharField(max_length=15)),
                ('Clarity_communication', models.CharField(max_length=15)),
                ('helpStudent', models.CharField(max_length=15)),
                ('presentation', models.CharField(max_length=15)),
                ('motivatesInterest', models.CharField(max_length=15)),
                ('co_opeartive', models.CharField(max_length=15)),
                ('newOutlook', models.CharField(max_length=15)),
                ('checking', models.CharField(max_length=15)),
                ('Seminar', models.CharField(max_length=15)),
                ('interaction', models.CharField(max_length=15)),
                ('effectiveness', models.CharField(max_length=15)),
            ],
        ),
    ]
