# Generated by Django 2.2.5 on 2020-06-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelMail', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherFeedback',
            new_name='Teacher_Feedback',
        ),
    ]
