# Generated by Django 2.2.5 on 2020-06-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelMail', '0002_auto_20200606_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_feedback',
            name='Branch',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
