# Generated by Django 2.2.5 on 2020-06-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelMail', '0003_auto_20200607_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_feedback',
            name='Clarity_communication',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='Knowledge',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='Regular_Punctual',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='Semester',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='Seminar',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='Teacher',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='checking',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='co_opeartive',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='effectiveness',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='helpStudent',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='interaction',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='motivatesInterest',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='newOutlook',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='presentation',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
