# Generated by Django 2.2.5 on 2020-06-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelMail', '0004_auto_20200607_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, null=True)),
                ('Email', models.EmailField(max_length=20, null=True)),
                ('Phone', models.IntegerField(max_length=10, null=True)),
            ],
        ),
    ]
