# Generated by Django 2.2.5 on 2020-06-08 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelMail', '0005_teacher_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher_Info',
        ),
    ]
