# Generated by Django 2.2.5 on 2020-06-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelMail', '0006_delete_teacher_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher_feedback',
            old_name='Teacher',
            new_name='Teacher_Name',
        ),
    ]
