# Generated by Django 2.2.5 on 2020-06-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelMail', '0007_auto_20200610_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_feedback',
            name='Regular_Punctual',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='Teacher_Name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
