# Generated by Django 2.2.5 on 2020-06-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelMail', '0009_auto_20200612_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_feedback',
            name='Branch',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='Clarity_communication',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='Knowledge',
            field=models.CharField(max_length=23, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='Semester',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='Seminar',
            field=models.CharField(max_length=33, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='checking',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='co_opeartive',
            field=models.CharField(max_length=29, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='effectiveness',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='helpStudent',
            field=models.CharField(max_length=26, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='interaction',
            field=models.CharField(max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='motivatesInterest',
            field=models.CharField(max_length=28, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='newOutlook',
            field=models.CharField(max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='presentation',
            field=models.CharField(max_length=27, null=True),
        ),
    ]
