# Generated by Django 2.2.5 on 2020-06-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelMail', '0010_auto_20200612_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_feedback',
            name='Knowledge',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
