# Generated by Django 2.2.5 on 2020-06-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelMail', '0011_auto_20200612_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_feedback',
            name='Subject_Title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='Clarity_communication',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='Seminar',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='checking',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='co_opeartive',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='effectiveness',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='helpStudent',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='interaction',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='motivatesInterest',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='newOutlook',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='presentation',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
