# Generated by Django 2.2.5 on 2020-06-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelMail', '0012_auto_20200613_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_feedback',
            name='Clarity_communication',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('VeryGood', 'VeryGood'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='Knowledge',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('VeryGood', 'VeryGood'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='Regular_Punctual',
            field=models.CharField(choices=[('Always Regular & Punctual', 'Always Regular & Punctual'), ('Not always Regular & Punctual', 'Not always Regular & Punctual'), ('Not Regular & Punctual', 'Not Regular & Punctual')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='Seminar',
            field=models.CharField(choices=[('Highly', 'Highly'), ('Moderate', 'Moderate'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='checking',
            field=models.CharField(choices=[('Highly', 'Highly'), ('Moderate', 'Moderate'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='co_opeartive',
            field=models.CharField(choices=[('Highly', 'Highly'), ('Moderate', 'Moderate'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='effectiveness',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('VeryGood', 'VeryGood'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='helpStudent',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('VeryGood', 'VeryGood'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='interaction',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('VeryGood', 'VeryGood'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='motivatesInterest',
            field=models.CharField(choices=[('Highly', 'Highly'), ('Moderate', 'Moderate'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='newOutlook',
            field=models.CharField(choices=[('Highly', 'Highly'), ('Moderate', 'Moderate'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_feedback',
            name='presentation',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('VeryGood', 'VeryGood'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20, null=True),
        ),
    ]
